# Generated by Django 4.2.5 on 2023-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_user_watchlist_comment_bid_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('ET', 'Entertainment'), ('GV', 'Gebruiksvoorwerpen'), ('IT', ' IT'), ('AU', "Auto's")], default='IT', max_length=2),
        ),
    ]
