# Generated by Django 4.2.5 on 2023-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
