# Generated by Django 4.2.5 on 2023-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='opening_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.ManyToManyField(related_name='bids', to='auctions.bid'),
        ),
    ]
