# Generated by Django 4.2.5 on 2023-09-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_allbids_alter_auction_user_alter_bid_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
    ]
