# Generated by Django 4.2.5 on 2023-09-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_bid_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='allbids',
            new_name='bids',
        ),
    ]
