# Generated by Django 4.2.5 on 2023-09-19 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auction_bids_alter_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bids',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
